export enum AlgorandGenesisHash {
  MainNet = 'wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=',
  TestNet = 'SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=',
  BetaNet = 'mFgazF+2uRS1tMiL9dsj01hJGySEmPN28B/TjjvpVW0='
}

export type AlgorandChainId = keyof typeof AlgorandGenesisHash

export interface AuthMessage {
  /** The domain name of the Verifier */
  domain: string
  /** Algorand account to authenticate with, encoded as a 32-bytes Algorand address */
  authAcc: string
  /** Unique random challenge of at least 15 characters and generated by the Verifier */
  challenge: string
  /** Algorand network identifier, encoded as a 32-bytes genesis hash of the network */
  chainId: AlgorandGenesisHash
  /** Optional, description of the Verifier */
  desc?: string
  /** Optional, metadata */
  meta?: string
}
