import { encode, decode } from '@msgpack/msgpack'

import { useNotifications } from './useNotifications'
import { usePeraWallet } from './usePeraWallet'

export interface AuthMessage {
  /** The domain name of the Verifier */
  domain: string
  /** Algorand account to authenticate with */
  authAcc: string
  /** Unique random nonce generated by the Verifier */
  nonce: string
  /** Optional, description of the Verifier */
  desc?: string
  /** Optional, metadata */
  meta?: string
}

export interface Session {
  authAcc: string
  accessToken: string
}

export const useAuth = () => {
  const router = useRouter()

  const { address, connectWallet, disconnectWallet, signData } = usePeraWallet()
  const { showNotification } = useNotifications()

  const sessionCookie = useCookie('session', { sameSite: 'strict', maxAge: 60 * 60 * 24 * 365, secure: true })

  const authMessage = ref<AuthMessage | null>(null)
  const isConfirmingSignIn = ref(false)

  const signInAbort = () => {
    disconnectWallet()
    authMessage.value = null
    showNotification('SIGN_IN_ABORT')
  }

  const signIn = async () => {
    try {
      await connectWallet()
      const message = await new Arc31ApiClient().request(address.value)
      // Remove the 'AX' prefix and decode the message from base64
      const decodedMessage = decode(Buffer.from(message.replace(/^AX/, ''), 'base64'))
      // Extract the authMessage from the decoded message
      const authMessageWrapper = decodedMessage as { 'arc31:j': AuthMessage }
      authMessage.value = authMessageWrapper['arc31:j']
    } catch (error) {
      signInAbort()
    }
  }

  const signInConfirm = async () => {
    try {
      isConfirmingSignIn.value = true
      if (!authMessage.value) {
        throw new Error('authMessage is null')
      }
      // Encode the authMessage and convert it to base64
      const encodedAuthMessage = encode({ 'arc31:j': authMessage.value })
      const base64AuthMessage = `AX${Buffer.from(encodedAuthMessage).toString('base64')}`
      // Convert the base64 message to bytes
      const messageBytes = Buffer.from(base64AuthMessage, 'base64')
      const signMessage = `You are going to login into ${authMessage.value.domain}. Please confirm that you are the owner of this wallet by signing this message.`
      // Sign the message
      const signedMessageBytes = await signData([{ data: messageBytes, message: signMessage }], authMessage.value.authAcc)
      // Convert the signed message to base64
      const signedMessageBase64 = Buffer.from(signedMessageBytes[0]).toString('base64')
      // Verify the signed message and update the session cookie
      const session = await new Arc31ApiClient().verify(signedMessageBase64, authMessage.value.authAcc)
      sessionCookie.value = JSON.stringify(session)
      authMessage.value = null
      showNotification('SIGN_IN_COMPLETE')
      router.push('/')
    } catch (error) {
      signInAbort()
    } finally {
      isConfirmingSignIn.value = false
    }
  }

  const signOut = () => {
    router.push('/signin')
    disconnectWallet()
    sessionCookie.value = null
    authMessage.value = null
    showNotification('SIGN_OUT_COMPLETE')
  }

  return {
    address,
    authMessage,
    isConfirmingSignIn,
    signInAbort,
    signIn,
    signInConfirm,
    signOut
  }
}
