export const ERR_ONLY_CREATOR_CAN_REKEY = 'only the creator can rekey an escrow contract'
export const ERR_ONLY_FACTORY_CAN_DELETE = 'only the factory can delete an escrow contract'
export const ERR_ALREADY_REGISTERED = 'already registered'
export const ERR_DOESNT_EXIST = 'does not exist'
export const ERR_FORBIDDEN = 'forbidden'
export const ERR_INVALID_APP = 'invalid app to register'
export const ERR_INVALID_CREATOR = 'invalid creator'