name: Mark stale PRs & Issues

on:
  schedule:
  - cron: 0 0 * * *  # Runs at 00:00 UTC every day.

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'algorandfoundation/ARCs'
    runs-on: ubuntu-latest
    name: Mark Stale Issues
    steps:
    - uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
      with:
        # General
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ascending: true # Since we have so many issues, the stale bot finds it hard to keep track. This makes sure that at least the oldest are removed.
        # Issue config
        stale-issue-message: There has been no activity on this issue for 1 week. It will be closed after 3 months of inactivity.
        close-issue-message: This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
        days-before-issue-stale: 7
        days-before-issue-close: 49 # 49 + 7 weeks = 3 months
        exempt-issue-labels: discussions-to
        stale-issue-label: w-stale
        # PR config
        stale-pr-message: There has been no activity on this pull request for 2 weeks. It will be closed after 3 months of inactivity. If you would like to move this PR forward, please respond to any outstanding feedback or add a comment indicating that you have addressed all required feedback and are ready for a review.
        close-pr-message: This pull request was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.
        days-before-pr-stale: 14
        days-before-pr-close: 42 # 42 + 14 weeks = 3 months
        stale-pr-label: w-stale